# Generated by Django 4.2.4 on 2023-09-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('cuit_compania', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_compania', models.CharField(max_length=255)),
                ('tipoiva_compania', models.PositiveSmallIntegerField()),
                ('domicilio_compania', models.CharField(max_length=255)),
                ('telefono_compania', models.CharField(max_length=45)),
                ('correo_compania', models.CharField(max_length=45)),
            ],
        ),
    ]
