# Generated by Django 4.2.4 on 2023-09-05 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_iva', models.CharField(max_length=45)),
                ('descripcion_iva', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['descripcion_iva'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_seccion', models.CharField(max_length=45)),
                ('descripcion_seccion', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['nombre_seccion'],
            },
        ),
        migrations.AlterModelOptions(
            name='compania',
            options={'ordering': ['nombre_compania']},
        ),
        migrations.AlterField(
            model_name='compania',
            name='correo_compania',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='compania',
            name='domicilio_compania',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='compania',
            name='telefono_compania',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.CreateModel(
            name='Asegurado',
            fields=[
                ('dni_asegurado', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('apellido_y_nombre_asegurado', models.CharField(max_length=255)),
                ('domicilio_asegurado', models.CharField(blank=True, max_length=255)),
                ('telefono_asegurado', models.CharField(blank=True, max_length=45)),
                ('correo_asegurado', models.CharField(blank=True, max_length=45)),
                ('cuit_asegurado', models.CharField(blank=True, max_length=45)),
                ('tipoiva_asegurado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguros.iva')),
            ],
            options={
                'ordering': ['apellido_y_nombre_asegurado'],
            },
        ),
        migrations.AlterField(
            model_name='compania',
            name='tipoiva_compania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguros.iva'),
        ),
    ]
