# Generated by Django 4.2.4 on 2023-09-05 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0002_iva_seccion_alter_compania_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccion',
            options={'ordering': ['nombre_seccion'], 'verbose_name_plural': 'Secciones'},
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poliza_nro', models.CharField(max_length=45)),
                ('endoso_nro', models.CharField(max_length=45)),
                ('renovacion_poliza', models.CharField(max_length=45)),
                ('descripcion_asegurado', models.CharField(max_length=255)),
                ('cobertura_asegurado', models.CharField(max_length=255)),
                ('suma_asegurada', models.CharField(max_length=45)),
                ('prima', models.CharField(max_length=45)),
                ('premio', models.CharField(max_length=45)),
                ('asegurado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguros.asegurado')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguros.compania')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguros.seccion')),
            ],
            options={
                'ordering': ['poliza_nro'],
            },
        ),
    ]
