# Generated by Django 4.2.4 on 2023-09-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0003_alter_seccion_options_poliza'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='vigencia_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='vigencia_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='renovacion_poliza',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
